# Generated by Django 4.0.5 on 2023-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(blank=True, max_length=60, null=True)),
                ('Age', models.CharField(max_length=2)),
                ('claimed', models.CharField(max_length=50)),
                ('claimed_date', models.DateField()),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.DateField()),
            ],
            options={
                'verbose_name': 'Stu_old',
                'verbose_name_plural': 'Stu_olds',
            },
        ),
    ]
