# Generated by Django 4.2.7 on 2023-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
