# Generated by Django 4.2.7 on 2024-02-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dept',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
