# Generated by Django 4.2.7 on 2024-02-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_users_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departnment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.users')),
            ],
            options={
                'verbose_name': 'Departnment',
                'verbose_name_plural': 'Departnments',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('submitted_by', models.CharField(max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('recpit_ref_NO', models.CharField(max_length=150)),
                ('recpit_from', models.CharField(max_length=150)),
                ('Reviewd_by', models.CharField(max_length=50)),
                ('Cleared_by', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('A_or_R_day', models.DateTimeField(null=True)),
                ('clerance_day', models.DateTimeField(null=True)),
                ('Cleared_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cleared_by', to='staff.users')),
                ('Reviewd_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reviewd_by', to='staff.users')),
                ('departnment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.departnment')),
                ('submitted_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to='staff.users')),
            ],
            options={
                'verbose_name': 'Spending',
                'verbose_name_plural': 'Spendings',
            },
        ),
        migrations.CreateModel(
            name='Allocation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.users')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.departnment')),
            ],
            options={
                'verbose_name': 'Allocation_history',
                'verbose_name_plural': 'Allocation_historys',
            },
        ),
        migrations.CreateModel(
            name='Allocated_cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('upadated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.departnment')),
            ],
        ),
    ]
