# Generated by Django 4.2.7 on 2024-02-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_users_dept'),
        ('cash', '0002_alter_allocated_cash_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departnment',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.users'),
        ),
    ]
