# Generated by Django 4.2.7 on 2024-02-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_allocation_history_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation_history',
            name='Allocated_by',
        ),
        migrations.AddField(
            model_name='allocation_history',
            name='action',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='allocation_history',
            name='current_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocation_history',
            name='possesd_by',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='allocation_history',
            name='possesd_for',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='allocation_history',
            name='typ',
            field=models.CharField(default='Not_allocation', max_length=50),
        ),
    ]
