# Generated by Django 4.2.7 on 2024-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_remove_allocation_history_allocated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_history',
            name='prev_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
