# Generated by Django 4.2.7 on 2024-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_allocation_history_prev_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_history',
            name='department_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
