# Generated by Django 4.2.7 on 2024-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_allocation_history_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_history',
            name='cleared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
