# Generated by Django 4.2.7 on 2024-02-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_allocation_history_cleared_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation_history',
            name='cleared_date',
        ),
    ]
