# Generated by Django 4.2.7 on 2024-02-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_remove_allocation_history_cleared_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='departnment_name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
