# Generated by Django 4.2.7 on 2024-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0012_alter_spending_cleared_by_alter_spending_reviewd_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='spend_catagory',
            field=models.CharField(default='', max_length=150),
        ),
    ]
