# Generated by Django 4.2.7 on 2024-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0013_spending_spend_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='recpit_req',
            field=models.BooleanField(default=True),
        ),
    ]
