# Generated by Django 4.2.7 on 2024-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0014_spending_recpit_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='finance_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
