# Generated by Django 4.2.7 on 2024-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0015_spending_finance_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='recpit_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spending',
            name='recpit_TIN_no',
            field=models.CharField(default='** unavilable **', max_length=150),
        ),
    ]
