# Generated by Django 4.2.7 on 2024-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0017_spending_recpit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='returned_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
