# Generated by Django 4.0.5 on 2023-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.PositiveIntegerField(blank=True, null=True)),
                ('registration', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('edu_lev', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=300)),
                ('occ', models.CharField(max_length=300)),
                ('cource', models.CharField(max_length=50)),
                ('cert_type', models.CharField(max_length=50)),
                ('photo_url', models.URLField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
