# Generated by Django 4.2.7 on 2023-11-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0003_payment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cert_rec_date',
            field=models.DateTimeField(null=True),
        ),
    ]
