# Generated by Django 4.2.7 on 2023-11-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0004_student_cert_rec_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='report_Generated',
            field=models.BooleanField(default=False),
        ),
    ]
