# Generated by Django 4.2.7 on 2024-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0006_payment_log_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourceAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
