# Generated by Django 4.2.7 on 2024-01-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0007_courceandprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_log',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
