# Generated by Django 4.2.7 on 2024-01-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0008_payment_log_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_log',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CERT.student'),
        ),
    ]
