# Generated by Django 4.2.7 on 2024-01-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0009_alter_payment_log_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_log',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
