# Generated by Django 4.2.7 on 2024-01-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERT', '0010_payment_log_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_log',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment_log',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
